name: setup-vcpkg
description: Install vcpkg, set environment variables, and cache the vcpkg binary packages
author: Patrick Kappl

inputs:
  committish:
    default: master
    required: false
    description: >-
      Committish of the vcpkg repository to checkout. This can be a branch, tag, or commit SHA.

  cache-key:
    required: true
    description: >-
      Key for the vcpkg cache. It should at least contain the OS and the compiler. A hash of the
      committish, CMakeLists.txt files, and/or vcpkg.json is also a good idea. See
      https://github.com/actions/cache for more details.

  cache-restore-keys:
    required: false
    description: >-
      Additional keys for restoring the vcpkg cache. They are used if the primary key does not find
      a cache. See https://github.com/actions/cache for more details.

  use-private-registry:
    default: 'false'
    required: false
    description: >-
      Whether to use our private vcpkg registry. This will authenticate the registry with the
      personal access token passed in private-registry-pat and download the vcpkg-configuration.json
      from its repository.

  private-registry-pat:
    required: false
    description: >-
      Personal access token with read access to the contents of our private vcpkg registry at
      https://github.com/fantana21/vcpkg-registry. Must be set when use-private-registry is true.

outputs:
  cache-hit:
    description: Whether the cache could be restored or not
    value: ${{ steps.store-cache-hit.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Set up vcpkg
      id: set-up-vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with:
        committish: ${{ inputs.COMMITTISH }}
        cache-key: ${{ inputs.cache-key }}
        cache-restore-keys: ${{ inputs.cache-restore-keys }}

    - name: Store cache hit
      id: store-cache-hit
      shell: bash
      run: echo "cache-hit=${{ steps.set-up-vcpkg.outputs.cache-hit }}" >> $env:GITHUB_OUTPUT

    - name: Add VCPKG_ROOT to PATH
      shell: bash
      run: echo "${{ env.VCPKG_ROOT }}" >> $GITHUB_PATH

    - name: Authenticate private registry
      if: inputs.use-private-registry == 'true'
      shell: bash
      run: git config --global credential.https://github.com/fantana21/vcpkg-registry.helper '!f() { echo username=unused; echo password=${{ inputs.private-registry-pat }}; }; f'

    - name: Download vcpkg-configuration.json from private registry
      if: inputs.use-private-registry == 'true'
      working-directory: ${{ env.VCPKG_ROOT }}
      shell: bash
      run: |
        curl -H 'Authorization: token ${{ inputs.private-registry-pat }}' -H 'Accept: application/vnd.github.v3.raw' -L https://api.github.com/repos/fantana21/vcpkg-registry/contents/vcpkg-configuration.json -O
